accounts/urls.py
from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    LogoutView,
    UserProfileView,
    UserEditProfileView,
    UserSubscriptionsView,
    UserFavoritesView,
    UserWatchListView,
    UserWatchHistoryView,
)

app_name = "accounts"

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
    path('profile', UserProfileView.as_view(), name='profile'),
    path('profile/edit', UserEditProfileView.as_view(), name='edit_profile'),
    path('subscriptions/', UserSubscriptionsView.as_view(), name='subscriptions'),
    
    path("my/favorites/", UserFavoritesView.as_view(), name="my_favorites"),
    path("my/watchlist/", UserWatchListView.as_view(), name="my_watchlist"),
    path("my/history/", UserWatchHistoryView.as_view(), name="my_history"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('refund-policy/', views.refund_policy, name='refund_policy'),
    path('pricing/', views.pricing, name='pricing'),
    
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/success/', views.checkout_success, name='checkout_success'),
    path('checkout/canceled/', views.checkout_canceled, name='checkout_canceled'),
    path('subscription/cancel/', views.cancel_subscription, name='cancel_subscription'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),
    path('details/<slug:slug>/', views.MovieDetailsView.as_view(), name='details'),
    path("<slug:slug>/favorite/", views.ToggleMovieFavoriteView.as_view(), name="toggle_favorite"),
    path("<slug:slug>/watchlist/", views.ToggleMovieWatchlistView.as_view(), name="toggle_watchlist"),
    path("<slug:slug>/review/", views.AddReviewView.as_view(), name="add_review"),
]

series/urls.py
from django.urls import path

from .views import (
    SeriesListView,
    SeriesDetailsView,
    ToggleFavoriteView,
    ToggleWatchListView,
    UpdateWatchHistoryView,
)

app_name = "series"

urlpatterns = [
    path("", SeriesListView.as_view(), name="index"),
    path("details/<slug:slug>/", SeriesDetailsView.as_view(), name="details"),
    path("<slug:slug>/favorite/", ToggleFavoriteView.as_view(), name="toggle_favorite"),
    path("<slug:slug>/watchlist/", ToggleWatchListView.as_view(), name="toggle_watchlist"),
    path("<slug:slug>/watch-history/", UpdateWatchHistoryView.as_view(), name="update_watch_history"),
]

webflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('accounts/', include("accounts.urls")),
    path('movies/', include("movies.urls")),
    path('series/', include("series.urls")),
    
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/gif" sizes="16x16">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
    <script src="https://kit.fontawesome.com/017eaf7e3f.js" crossorigin="anonymous"></script>
    <title>Webflix | Free movies & TV Shows</title>
    {% block styles %}{% endblock %}
</head>
<body class="dark-mode" alt="{{ request.get_host }}">

<div class="container-fluid">
    <div class="row main-row">
        <div class="sidebar">
            <a class="page-header logo-app" href="/">
                <img src="{% static "img/logo.png" %}" alt="logo">
            </a>
            <div class="nav-bar-container">
                <nav class="navbar bg-light left-navbar">
                    <ul class="navbar-nav">
                        <a href="{% url 'core:pricing' %}" class="btn btn-subscription">
                            <i class="fas fa-star"></i> Subscribe now !</a>
                        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'core:home' %}">
                                <i class="fas fa-home"></i>
                                Home
                            </a>
                        </li>
                        <li class="nav-item {% if request.path == '/movies/' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'movies:index' %}">
                                <i class="fas fa-film"></i> Movies
                            </a>
                        </li>
                        <li class="nav-item {% if request.path == '/series/' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'series:index' %}">
                                <i class="fas fa-desktop"></i> TV Shows
                            </a>
                        </li>
                        {% comment %} <li class="nav-item">
                            <a class="nav-link" href="">
                                <i class="fas fa-bullseye"></i> Tv Channels
                            </a>
                        </li> {% endcomment %}
                        {% if request.user.is_authenticated %}
                            <li class="nav-item {% if request.path == '/mylist/' %}active{% endif %}">
                                <a class="nav-link" href=""><i class="fas fa-folder"></i> My list
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <nav class="navbar bg-light left-navbar bottom-navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:faq' %}">
                            <i class="fas fa-question-circle"></i> FAQ & Support
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:privacy_policy' %}">
                            <i class="fas fa-lock"></i> Privacy Policy
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:refund_policy' %}">
                            <i class="fas fa-dollar-sign"></i> Refund Policy
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="close-menu-left-btn"></div>
        <div class="main">
            <div class="xs-header">
                <button class="btn btn-primary float-left menu-left-btn"><i class="fas fa-bars"></i></button>
                <img src="{% static "img/logo.png" %}" alt="logo">
                <div class="btn-group float-right ">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <span class="for-desktop"> {{ request.user.get_full_name }} </span>
                            {% if request.user.avatar %}
                                <img src="{{ request.user.avatar.url }}" alt="">
                            {% else %}
                                <i class="fas fa-user" style="margin-top: 10px;"></i>
                            {% endif %}
                    </button>
                    <div class="dropdown-menu dropdown-login">
                        <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                            <i class="fas fa-user"></i> My Profile
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">
                            <i class="fas fa-user-edit"></i> Edit Profile
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:subscriptions' %}">
                            <i class="fas fa-star"></i>Subscriptions
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user-lock"></i> Change password
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:my_favorites' %}">
                            <i class="fas fa-heart"></i> My Favorites
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:my_watchlist' %}">
                            <i class="fas fa-bookmark"></i> My Watchlist
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:my_history' %}">
                            <i class="fas fa-history"></i> Watch History
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </div>
                    <button class="btn btn-primary float-right open-login"><i class="fas fas fa-user"></i></button>
                    <button class="btn btn-primary float-right search-btn"><i class="fas fa-search"></i></button>
                </div>
            </div>
            <div class="row top-nav">
                <div class="col-sm-3 col-md-3 ">
                    <div class="tab-title"></div>
                </div>
                <div class="col-sm-6 col-md-6 search-form">
                    <form action="" class="navbar-form" role="search">
                        <div class="search-group">
                            <i class="fas fa-search"></i>
                            <input type="text" class="form-control"
                                   placeholder="Movies,Tv Shows , Tv Channels , Actors ..." name="q">
                            <button class="btn btn-default" type="submit">Search</button>
                        </div>
                    </form>
                    <button class="btn btn-primary float-right for-phone search-btn-close"><i class="fas fa-times"></i>
                    </button>

                </div>
                <div class="col-sm-3 col-md-3 account-action for-desktop">
                    {% if request.user.is_authenticated %}
                        <div class="btn-group float-right ">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="for-desktop"> {{ request.user.get_full_name }} </span>
                                {% if request.user.avatar %}
                                    <img src="{{ request.user.avatar.url }}" alt="">
                                {% else %}
                                    <i class="fas fa-user" style="margin-top: 10px;"></i>
                                {% endif %}
                            </button>
                            <div class="dropdown-menu dropdown-login">
                                <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                                    <i class="fas fa-user"></i> My Profile
                                </a>
                                <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">
                                    <i class="fas fa-user-edit"></i> Edit Profile
                                </a>
                                <a class="dropdown-item" href="{% url 'accounts:subscriptions' %}">
                                    <i class="fas fa-star"></i>Subscriptions
                                </a>
                                <a class="dropdown-item" href="{% url 'accounts:my_favorites' %}">
                                    <i class="fas fa-heart"></i> My Favorites
                                </a>
                                <a class="dropdown-item" href="{% url 'accounts:my_watchlist' %}">
                                    <i class="fas fa-bookmark"></i> My Watchlist
                                </a>
                                <a class="dropdown-item" href="{% url 'accounts:my_history' %}">
                                    <i class="fas fa-history"></i> Watch History
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                    <i class="fas fa-sign-out-alt"></i> Logout
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <div class="float-right">
                            <a href="{% url 'accounts:register' %}" class="btn btn-link"> Register </a>
                            <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login </a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="{% static 'js/app.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <!-- Hero Section with Featured Content -->
    {% if content_type != 'series' and featured_movie %}
        <div class="hero-section" style="background-image: url('{{ featured_movie.cover }}')">
            <div class="hero-overlay">
                <div class="container">
                    <div class="hero-content">
                        <span class="content-type">Movie</span>
                        <h1>{{ featured_movie.title }}</h1>
                        <p>{{ featured_movie.description|truncatechars:200 }}</p>
                        <div class="hero-buttons">
                            <a href="{% url 'movies:details' featured_movie.slug %}" class="btn btn-primary btn-lg">
                                <i class="fas fa-play"></i> Watch Now
                            </a>
                            {% if featured_movie.trailer_url %}
                            <a href="{{ featured_movie.trailer_url }}" class="btn btn-secondary btn-lg">
                                <i class="fas fa-film"></i> Watch Trailer
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% elif content_type != 'movies' and featured_series %}
        <div class="hero-section" style="background-image: url('{{ featured_series.cover }}')">
            <div class="hero-overlay">
                <div class="container">
                    <div class="hero-content">
                        <span class="content-type">TV Series</span>
                        <h1>{{ featured_series.title }}</h1>
                        <p>{{ featured_series.description|truncatechars:200 }}</p>
                        <div class="hero-buttons">
                            <a href="{% url 'series:details' featured_series.slug %}" class="btn btn-primary btn-lg">
                                <i class="fas fa-play"></i> Watch Now
                            </a>
                            {% if featured_series.trailer_url %}
                            <a href="{{ featured_series.trailer_url }}" class="btn btn-secondary btn-lg">
                                <i class="fas fa-film"></i> Watch Trailer
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- Filters Section -->
    <div class="container">
        <div class="filters-section">
            <div class="row align-items-center">
                <div class="col-md-4">
                    <div class="content-type-filter">
                        <a href="?type=all" class="btn btn-secondary {% if content_type == 'all' %}active{% endif %}">
                            All
                        </a>
                        <a href="?type=movies" class="btn btn-secondary {% if content_type == 'movies' %}active{% endif %}">
                            Movies
                        </a>
                        <a href="?type=series" class="btn btn-secondary {% if content_type == 'series' %}active{% endif %}">
                            TV Series
                        </a>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="sort-options float-right">
                        <a href="?sort=newest" class="btn btn-secondary {% if sort == 'newest' %}active{% endif %}">
                            <i class="far fa-clock"></i><span class="d-none d-md-inline"> Newest</span>
                        </a>
                        <a href="?sort=views" class="btn btn-secondary {% if sort == 'views' %}active{% endif %}">
                            <i class="far fa-eye"></i><span class="d-none d-md-inline"> Views</span>
                        </a>
                        <a href="?sort=rating" class="btn btn-secondary {% if sort == 'rating' %}active{% endif %}">
                            <i class="fas fa-star-half-alt"></i><span class="d-none d-md-inline"> Rating</span>
                        </a>
                        <a href="?sort=imdb" class="btn btn-secondary {% if sort == 'imdb' %}active{% endif %}">
                            <i class="fab fa-imdb"></i><span class="d-none d-md-inline"> IMDb</span>
                        </a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="genre-filter float-right">
                        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            All Genres
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <a class="dropdown-item active" href="?genre=all">All Genres</a>
                            {% for genre in genres %}
                                <a class="dropdown-item {% if selected_genre == genre.slug %}active{% endif %}" 
                                   href="?genre={{ genre.slug }}">{{ genre.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% if content_type != 'series' %}
            <!-- Movie Sections -->
            <section class="movie-section">
                <div class="section-header">
                    <h2>Trending Movies</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for movie in trending_movies %}
                        {% include 'movies/includes/movie_card.html' with movie=movie %}
                    {% endfor %}
                </div>
            </section>

            <section class="movie-section">
                <div class="section-header">
                    <h2>Latest Movies</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for movie in latest_movies %}
                        {% include 'movies/includes/movie_card.html' with movie=movie %}
                    {% endfor %}
                </div>
            </section>
        {% endif %}

        {% if content_type != 'series' %}
            <!-- Series Sections -->
            <section class="movie-section">
                <div class="section-header">
                    <h2>Trending Series</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for series in trending_series %}
                        {% include 'series/includes/series_card.html' with series=series %}
                    {% endfor %}
                </div>
            </section>

            <section class="movie-section">
                <div class="section-header">
                    <h2>Latest Series</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for series in latest_series %}
                        {% include 'series/includes/series_card.html' with series=series %}
                    {% endfor %}
                </div>
            </section>
        {% endif %}

        {% if content_type != 'series' %}
            <section class="movie-section">
                <div class="section-header">
                    <h2>Top Rated Movies</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for movie in top_rated_movies %}
                        {% include 'movies/includes/movie_card.html' with movie=movie %}
                    {% endfor %}
                </div>
            </section>
        {% endif %}

        {% if content_type != 'movies' %}
            <section class="movie-section">
                <div class="section-header">
                    <h2>Top Rated Series</h2>
                    <a href="" class="view-all">View All</a>
                </div>
                <div class="movie-slider">
                    {% for series in top_rated_series %}
                        {% include 'series/includes/series_card.html' with series=series %}
                    {% endfor %}
                </div>
            </section>
        {% endif %}
    </div>
{% endblock %}

templates/memberships.html
{% load static %}

<!DOCTYPE>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/gif" sizes="16x16">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://kit.fontawesome.com/017eaf7e3f.js" crossorigin="anonymous"></script>
    <title>Webflix - Subscriptions</title>
</head>

<body class="light-mode">
<div class="login-page-bg"></div>
<div class="login-page-bg-blur"></div>
<div class="login-page-content">
    <img src="{% static "img/logo.png" %}" alt="logo">
    {% include 'messages.html' %}
    <form action="{% url 'core:submit-payment-method' %}" method="post">
        {% csrf_token %}

        <div class="tab-title">Subscribe now!</div>
        <div id="subscribe-plan">
            <div class="subscribe-title">
                <span>1</span>
                <h5>Select a plan that work for you,All Plans offer </h5>
            </div>
            <br>

            <label {% if current_membership == "Free" %} style="pointer-events:none" {% endif %} class="pack {% if current_membership == "Free" %} active {% endif %}" alt="1">
                <div>
                    <input type="radio" name="package" required="required" value="1">

                    <h5>Free</h5>
                    <span>0 USD</span>
                    {% if current_membership == "Free" %} <p>Currently active</p> {% endif %}
                </div>
            </label>

            <label {% if current_membership == "Monthly" %} style="pointer-events:none" {% endif %} class="pack {% if current_membership == "Monthly" %} active {% endif %}" alt="2">
                <div>
                    <input type="radio" name="package" required="required" value="2">

                    <h5>Monthly</h5>
                    <span>15 USD</span>
                    {% if current_membership == "Monthly" %} <p>Currently active</p> {% endif %}
                </div>
            </label>

            <label {% if current_membership == "Daily" %} style="pointer-events:none" {% endif %} class="pack {% if current_membership == "Daily" %} active {% endif %}" alt="3">
                <div>
                    <input type="radio" name="package" required="required" value="3">

                    <h5>Daily</h5>
                    <span>1 USD</span>
                    {% if current_membership == "Daily" %} <p>Currently active</p> {% endif %}
                </div>
            </label>
            <p class="error-plan">• Please select a plan</p>
            <span id="go-payment-method" class="float-right btn btn-primary">CONTINUE <i class="fas fa-chevron-right" aria-hidden="true"></i></span>
        </div>
        <div id="payment-method">
            <div class="subscribe-title" id="selected_pack">
                <span>1</span>

                <h5>Daily</h5>
                <span class="fas fa-check float-right" aria-hidden="true"></span>
                <span class="float-right price-step-1">1 USD</span>
            </div>
            <div class="subscribe-title">
                <span>2</span>
                <h5>Please select your payment method : </h5>
            </div>
            <br>

            <label class="payment" alt="paypal">
                <div>
                    <i class="fab fa-paypal" aria-hidden="true"></i>
                    <input type="radio" id="form_method_0" name="method" required="required" value="paypal">
                    <h4> PayPal</h4>
                    <i class="fas fa-check" aria-hidden="true"></i>
                </div>
            </label>

            <label class="payment" alt="card">
                <div>
                    <i class="far fa-credit-card" aria-hidden="true"></i>
                    <input type="radio" id="form_method_1" name="method" required="required" value="card">
                    <h4> Credit Card</h4>
                    <i class="fas fa-check" aria-hidden="true"></i>
                </div>
            </label>

            <p class="error-method">• Please select a payment methode</p>
            <button id="go-to-pay" type="submit" class="float-right btn btn-primary"><i class="fas fa-check" aria-hidden="true"></i> PAY NOW</button>
        </div>
    </form>
</div>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/messages.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        <a class="close" href="#" data-dismiss="alert">×</a>
        {{ message }}
    </div>
{% endfor %}